name: Release with artifacts

inputs:
  is-prerelease:
    required: true

runs:
  using: composite
  steps:
    - name: Download artifacts (win-x64)
      uses: actions/download-artifact@v4
      with:
        name: glazewm-win-x64-${{ github.sha }}
        path: artifacts/win-x64

    - name: Download artifacts (win-x86)
      uses: actions/download-artifact@v4
      with:
        name: glazewm-win-x86-${{ github.sha }}
        path: artifacts/win-x86

    - uses: glzr-io/actions/semantic-release@main
      with:
        is-prerelease: ${{ inputs.is-prerelease }}
        prerelease_tag: nightly
        gh-publish: true
        gh-draft-release: ${{ !inputs.is-prerelease }}
        gh-token: ${{ github.token }}
        gh-assets: |
          [
            {
              "path": "artifacts/win-x64/GlazeWM.exe",
              "name": "GlazeWM_x64_${nextRelease.gitTag}"
            },
            {
              "path": "artifacts/win-x86/GlazeWM.exe",
              "name": "GlazeWM_x86_${nextRelease.gitTag}"
            }
          ]
