[package]
name = "wm"
version = "0.0.0"
description = "GlazeWM is a tiling window manager for Windows inspired by i3 and Polybar."
repository = "https://github.com/glzr-io/glazewm"
license = "GPL-3"
edition = "2021"
default-run = "glazewm"

[[bin]]
name = "glazewm"
path = "src/main.rs"

[features]
no_console = []
ui_access = []

[build-dependencies]
tauri-winres = { workspace = true }

[dependencies]
wm-common = { path = "../wm-common" }
wm-ipc-client = { path = "../wm-ipc-client" }
anyhow = { workspace = true }
clap = { workspace = true }
ambassador = "0.4"
enum-as-inner = "0.6"
futures-util = { workspace = true }
home = "0.5"
uuid = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_yaml = "0.9"
regex = "1"
tokio = { workspace = true }
tracing-appender = "0.2"
tokio-tungstenite = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
tray-icon = "0.14"
windows = { version = "0.52", features = [
  "implement",
  "Win32_Devices_HumanInterfaceDevice",
  "Win32_Foundation",
  "Win32_Graphics_Dwm",
  "Win32_Graphics_Gdi",
  "Win32_Security",
  "Win32_System_Com",
  "Win32_System_Environment",
  "Win32_System_LibraryLoader",
  "Win32_System_Registry",
  "Win32_System_RemoteDesktop",
  "Win32_System_SystemServices",
  "Win32_System_Threading",
  "Win32_UI_Accessibility",
  "Win32_UI_HiDpi",
  "Win32_UI_Input_Ime",
  "Win32_UI_Input_KeyboardAndMouse",
  "Win32_UI_Shell_Common",
  "Win32_UI_TextServices",
  "Win32_UI_WindowsAndMessaging",
] }
windows-interface = { version = "0.52" }
