name: Lint check

on: push

jobs:
  lint-check:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "7.x"
          cache: true

      - name: Run dotnet format
        run: dotnet format --verify-no-changes
