name: Winget Release
on:
  release:
    types: [released]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: vedantmgoyal2009/winget-releaser@v2
        with:
          identifier: glzr-io.glazewm
          installers-regex: 'glazewm-[0-9.]+\.exe$'
          token: ${{ secrets.WINGET_TOKEN }}