name: Winget release
on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: vedantmgoyal2009/winget-releaser@v2
        with:
          identifier: glzr-io.glazewm
          installers-regex: 'glazewm-[0-9.]+\.exe$'
          token: ${{ secrets.WINGET_TOKEN }}
