name: Winget release

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: vedantmgoyal9/winget-releaser@a3ac67b0c3026bc335a33b722188e3ec769d6a64
        with:
          identifier: glzr-io.glazewm
          installers-regex: 'glazewm-v[0-9.]+\.exe$'
          token: ${{ secrets.WINGET_TOKEN }}
